server:
  port: 8888

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service/
          predicates:
            - Path=/users/**
        - id: department-service
          uri: lb://department-service/
          predicates:
            - Path=/departments/**

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}