server:
  port: 8888

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9001/
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service/
          predicates:
            - Path=/users/**
        - id: department-service
          uri: lb://department-service/
          predicates:
            - Path=/departments/**
