server:
  port: 0

spring:
  application:
    name: department-service
  config:
    import: configserver:http://localhost:9001/
  zipkin:
    base-url: http://127.0.0.1:9411/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.sleuth: DEBUG
    zipkin2: DEBUG
