server:
  port: 0

spring:
  application:
    name: department-service
  config:
    import: configserver:http://localhost:9001/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: info
